#!/usr/bin/env node
/**
 * Assemble the deployable site into dist/.
 *
 * There is no bundler and no transpile step. The page imports the engine as
 * plain ES modules, so "building" is copying four directories into one that
 * can be served from any static host at any path.
 *
 * The engine files are copied rather than duplicated by hand, which is the
 * point: the page and the pipeline run the same analysis, and there is no
 * second copy to drift.
 *
 * Usage:
 *   node build.mjs                 assemble into dist/
 *   node build.mjs --out ../site   assemble somewhere else
 */

import { cp, rm, mkdir, readdir, stat, readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const argv = process.argv.slice(2);
const outFlag = argv.indexOf('--out');
const OUT = resolve(HERE, outFlag === -1 ? 'dist' : argv[outFlag + 1]);
const clean = !argv.includes('--no-clean');

/** What goes where, relative to the project root and to dist. */
const COPY = [
  { from: 'web', to: '.' },
  { from: 'engine', to: 'engine' },
  { from: 'prompts', to: 'prompts' },
  { from: 'data/demo-dataset.json', to: 'data/demo-dataset.json' },
];

async function dirSize(path) {
  let bytes = 0;
  let files = 0;
  for (const entry of await readdir(path, { withFileTypes: true })) {
    const full = join(path, entry.name);
    if (entry.isDirectory()) {
      const inner = await dirSize(full);
      bytes += inner.bytes;
      files += inner.files;
    } else {
      bytes += (await stat(full)).size;
      files += 1;
    }
  }
  return { bytes, files };
}

/** The three prompts, in the order the page shows them. */
const PROMPTS = [
  { n: 1, title: 'Build the database', file: 'prompts/prompt-1-build-the-database.md' },
  { n: 2, title: 'Coach me with Jev', file: 'prompts/prompt-2-coach-me-with-jev.md' },
  { n: 3, title: 'Prep me for a call', file: 'prompts/prompt-3-prep-me-for-a-call.md' },
];

/**
 * Inline the prompt markdown into a generated module.
 *
 * The page could fetch the .md files directly, and locally that works. On
 * GitHub Pages it is at the mercy of whether the Jekyll layer decides a
 * markdown file is a page to render or a file to serve. Generating a module
 * from the same .md files keeps one source of truth in the repository and
 * removes the question entirely, along with three network round trips.
 */
async function generatePrompts() {
  const entries = [];
  for (const p of PROMPTS) {
    const text = (await readFile(resolve(HERE, p.file), 'utf8')).trim();
    entries.push(
      `  { n: ${p.n}, title: ${JSON.stringify(p.title)}, file: ${JSON.stringify(p.file)},\n` +
        `    text: ${JSON.stringify(text)} },`
    );
  }

  return (
    '// Generated by build.mjs from prompts/*.md. Do not edit.\n' +
    '// Edit the markdown in prompts/ and run `npm run build`.\n' +
    'export const PROMPTS = [\n' +
    entries.join('\n') +
    '\n];\n'
  );
}

async function main() {
  if (clean) await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const item of COPY) {
    const from = resolve(HERE, item.from);
    const to = resolve(OUT, item.to);
    await mkdir(dirname(to), { recursive: true });
    await cp(from, to, { recursive: true });
  }

  await writeFile(resolve(OUT, 'prompts.generated.js'), await generatePrompts());

  // Static hosts that run Jekyll otherwise get to decide what a .md file is.
  await writeFile(resolve(OUT, '.nojekyll'), '');

  const { bytes, files } = await dirSize(OUT);
  console.log(`Built ${OUT}`);
  console.log(`  ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
  console.log(`  serve it from any path: it uses no absolute URLs`);
}

main().catch((err) => {
  console.error(`build failed: ${err.message}`);
  process.exitCode = 1;
});
